sequenceDiagram
    participant browser
    participant server
    participant database

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server->>database: Create new element "li"
    activate database
    database->>server: New element "li" created successfully
    desactivate database
    server->>browser: Element created successfully

    reload page
    show new element

    desactivate server
