browser ->
HTTP GET https://studies.cs.helsinki.fi/exampleapp/spa

<- server
HTML code


browser ->
HTTP GET https://studies.cs.helsinki.fi/exampleapp/spa/main.css

<- server
main.css


browser ->
HTTP GET https://studies.cs.helsinki.fi/exampleapp/spa/main.js

<- server
main.js


browser ->
HTTP GET https://studies.cs.helsinki.fi/exampleapp/spa/data.json

<- server
data.json 